INSERT INTO
    directors (first_name, last_name)
VALUES
    ('Frank', 'Darabont')
  , ('Martin', 'Scorsese')
  , ('Christopher', 'Nolan')
  , ('Ridley', 'Scott')
  , ('Paul', 'Verhoeven')
  , ('Lana', 'Wachowski')
  , ('John', 'McTiernan')
  , ('Rob', 'Reiner')
  , ('Jane', 'Campion')
  , ('David', 'Mackenzie')
  , ('Sergio', 'Leone')
  , ('Clint', 'Eastwood')