-- ALL FILMS
SELECT * FROM films;

-- ALL FILMS ORDERED BY RATING DESCENDING
SELECT * FROM films
ORDER BY score DESC;

-- ALL FILMS ORDERED BY RELEASE YEAR ASCENDING
SELECT * FROM films
ORDER BY release_year ASC;

-- ALL FILMS WITH A RATING OF 8 OR HIGHER
SELECT * FROM films
WHERE score >= 8;

-- ALL FILMS WITH A RATING OF 7 OR LOWER
SELECT * FROM films
WHERE score <= 7;

-- ALL FILMS RELEASED IN 1990
SELECT * FROM films
WHERE release_year = 1990;

-- ALL FILMS RELEASED BEFORE 2000
SELECT * FROM films
WHERE release_year < 2000;

-- ALL FILMS RELEASED AFTER 1990
SELECT * FROM films
WHERE release_year > 1990;

-- ALL FILMS RELEASED BETWEEN 1990 AND 1999
SELECT * FROM films
WHERE release_year BETWEEN 1990 AND 1999;

-- ALL FILMS WITH GENRE OF SCIFI
SELECT * FROM films
WHERE genre = 'SciFi';

-- ALL FILMS WITH GENRE OF WESTERN OR SCIFI
SELECT * FROM films
WHERE genre IN ('Western', 'SciFi');

-- ALL FILMS APART WITH GENRE OF SCIFI
SELECT * FROM films
WHERE genre != 'SciFi';

-- ALL FILMS WITH GENRE OF WESTERN RELEASED BEFORE 2000
SELECT * FROM films
WHERE genre = 'Western' AND release_year < 2000;

-- ALL MATRIX FILMS
SELECT * FROM films
WHERE title LIKE '%Matrix%';

-- THE AVERAGE FILM RATING
SELECT AVG(score) FROM films;

-- THE TOTAL NUMBER OF FILMS
SELECT COUNT(*) FROM films;

-- THE AVERAGE FILM RATING BY GENRE
SELECT genre, AVG(score) FROM films
GROUP BY genre;

-- ALL FILMS WITH THEIR DIRECTORS
SELECT title AS film, name AS director
FROM films
JOIN directors
ON films.directorid = directors.id;

-- ALL DIRECTORS AND THE NUMBER OF FILMS THEY HAVE DIRECTED
SELECT name AS director, COUNT(*) AS films 
FROM films
JOIN directors
ON films.directorid = directors.id
GROUP BY name;